-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            size = 8,
        },
        rounding = 15,
    },
    general = {
        border_size = 1,
        gaps_in = 1,
        gaps_out = 8,
    },
    misc = {
        disable_splash_rendering = true,
    },
})

-- Monitors
hl.monitor({
    output = "desc:Samsung Electric Company C24F390 H4ZN402698",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "desc:AU Optronics 0x7EAD 0x00007EAD",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "-1920x0",
    scale = 1,
    cm = "srgb",
})
