# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#130d09

# Main text color
theme[main_fg]=#f8e1d5

# Title color for boxes
theme[title]=#f8e1d5

# Highlight color for keyboard shortcuts
theme[hi_fg]=#f5ba94

# Background color of selected item in processes box
theme[selected_bg]=#211812

# Foreground color of selected item in processes box
theme[selected_fg]=#f5ba94

# Color of inactive/disabled text
theme[inactive_fg]=#837268

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#fff9eb

# Background color of the percentage meters
theme[meter_bg]=#837268

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#fff9eb

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#ffab97
theme[mem_box]=#ffdaae
theme[net_box]=#f8ad8a
theme[proc_box]=#ffa2bd

# Box divider line and small boxes line color
theme[div_line]=#54453c

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#ffdaae
theme[temp_mid]=#ffeee3
theme[temp_end]=#ff9a6a

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#ffdb94
theme[cpu_mid]=#b3d27e
theme[cpu_end]=#ffbcbb

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#ffab97
theme[free_mid]=#ffbcbb
theme[free_end]=#ffa2bd

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#b3d27e
theme[cached_mid]=#ffa2bd
theme[cached_end]=#ffbcbb

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#ffc098
theme[available_mid]=#f8ad8a
theme[available_end]=#ff9a6a

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#ffdaae
theme[used_mid]=#ffdb94
theme[used_end]=#e1df87

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#ffc098
theme[download_mid]=#f8ad8a
theme[download_end]=#ff9a6a

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#ffdaae
theme[upload_mid]=#ffdb94
theme[upload_end]=#e1df87

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#b3d27e
theme[process_mid]=#ffbcbb
theme[process_end]=#ffab97
